### ISSUE TITLE
Please remove reference to artist in promt in Lab3

### ISSUE THREAD

**Issue by vilelamc** [aws-samples/generative-ai-on-aws-immersion-day#12]
In one of the Stable Diffusion prompts in Lab 3 the name of artist Greg Rutkowski is included. I was checking the web site of the artist, in https://www.artstation.com/rutkowski, and the first thing I noticed was a atatement "Say no to AI generated images".
Please respect the artist and remove his name from the prompt in the Jupyter notebook

**Comment by omerh** [comment]
https://github.com/aws-samples/generative-ai-on-aws-immersion-day/commit/e3f038c3fb2d75bd599eec182cc832b4becea91d
