### ISSUE TITLE
Lab1 error: sharded is not supported for AutoModel

### ISSUE THREAD

**Issue by peerjako-aws** [aws-samples/generative-ai-on-aws-immersion-day#13]
When trying to deploy the falcon40b model llm_model.deploy it fails creating the SageMaker Endpoint due to container health check fails. When looking into the CloudWatch logs there are errors: "sharded is not supported for AutoModel"

> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
    model = get_model(model_id, revision, sharded, quantize, trust_remote_code)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 286, in get_model
    raise ValueError("sharded is not supported for AutoModel")

**Comment by omerh** [comment]
Hey
This issue was fixed
