### ISSUE TITLE
Lab 4 - Lambda fails to call Kendra

### ISSUE THREAD

**Issue by mmeidlinger** [aws-samples/generative-ai-on-aws-immersion-day#7]
Getting Internal Server errors
![image](https://github.com/aws-samples/generative-ai-on-aws-immersion-day/assets/7677356/4b636f08-9515-419a-b622-757dc93b966d)

Checking the Lambda function logs, it looks like Lambda can't call Kendra. Kendra index is populated with the docs and I verified Lambda has the correct index id.
```
[ERROR] KeyError: 'client'
Traceback (most recent call last):
  File "/var/task/rag_app.py", line 85, in lambda_handler
    retriever = AmazonKendraRetriever(
  File "/var/task/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "pydantic/main.py", line 1050, in pydantic.main.validate_model
    input_data = validator(cls_, input_data)
  File "/var/task/langchain/retrievers/kendra.py", line 191, in create_client
    if values["client"] is not None:
```

**Comment by omerh** [comment]
Hey @mmeidlinger 
The lambda should have environment variable set with the Kendra index id in `KENDRA_INDEX_ID`, along with `SM_ENDPOINT_NAME`, and `SM_MODEL_TYPE`

You can set them in the [CF template](https://github.com/aws-samples/generative-ai-on-aws-immersion-day/blob/main/lab4/template.yml), and run `sam build`, `sam deploy` or go to the lambda environment variable configuration, and edit it there.

**Comment by mmeidlinger** [comment]
I did set these, I don't think this is a config issue:
![image](https://github.com/aws-samples/generative-ai-on-aws-immersion-day/assets/7677356/123339c2-dacd-417e-a2a3-a13a8b8b154e)
![image](https://github.com/aws-samples/generative-ai-on-aws-immersion-day/assets/7677356/b2ebc2b4-0330-45e6-86a5-baaec376ab9a)

**Comment by omerh** [comment]
Can you please pull latest changes, build and update the Lambda.
We are now using Langchain for using Kendra retrieve API
